project:
  type: website
  output-dir: docs


website:
  title: "GRRAS-COSMIN"
  description: "Website to present the ongoing project GRRAS-COSMIN developing updated reporting guidelines for agreement and reliability studies. "
  site-url: "grass-cosmin.com"
  announcement: 
    content: |
      **New** â€” we are currently looking for panelists for our Delphi study.  
      <a href="mailto:merle-marie@charite.de" class="email-link" title="Email Merle-Marie">
        <i class="bi bi-envelope-fill"></i> Feel free to reach out if you are interested.
      </a>
    position: below-navbar 
 # reader-mode: true
  navbar:
    right:
      - href: index.qmd
        text: Home
      - projects.qmd
      - team.qmd
    logo: "images/grras-cosmin-logo-small.png"
    background: "#009999"
  page-footer:
    border: true
    background: "#009999"
    left: "This website is under the [CC BY 4.0 license](https://creativecommons.org/licenses/by/4.0/)."  
    right: 
      <img src="images/dfg-logo-blau.jpg" alt="DFG logo" height="40" style="margin-right:10px;">

        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    self-contained: true
    grid:
      body-width: "1200px"

    
editor: visual
              

sidebar:
  style: "floating"   # or "docked"
  contents: auto

